// Import
import {FC} from "react";
import Head from "next/head";

interface IProps {
	firstName: string;
	lastName: string;
	profileImageUrl: string;
}

const MetaTag: FC<IProps> = ({firstName, lastName, profileImageUrl}) => {
	return (
		<Head>
			{/* <!-- Website Title --> */}
			<title>{`${firstName} ${lastName}`} | Dashboard</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href={profileImageUrl} />
		</Head>
	);
};

export default MetaTag;
