// Imports
import {FC} from "react";
import Head from "next/head";

// Components
import Footer from "../Footer";
import Navbar from "../Navbar";

interface ILayout {
	pageTitle: any;
	children: React.ReactNode;
}

const Layout: FC<ILayout> = ({children, pageTitle}) => {
	return (
		<>
			<Head>
				<title>{`${pageTitle} | Inventory Management Software`}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/Logos/BlueInventory favicon Two.png" />
			</Head>

			<Navbar />

			<section className="pt-16">{children}</section>

			<Footer />
		</>
	);
};

export default Layout;
