// Imports
import {FC} from "react";
import Head from "next/head";

// Components
import Footer from "../Footer";
import Navbar from "../Navbar";

interface ILayout {
	pageTitle: any;
	footerMenuLinks: [
		{
			node: {
				id: string;
				url: string;
				label: string;
			};
		}
	];
	navbarMenuLinks: [
		{
			node: {
				id: string;
				url: string;
				label: string;
			};
		}
	];
	industriesMenuLinks: [
		{
			node: {
				id: string;
				url: string;
				label: string;
			};
		}
	];
	themesOptionsContent: {
		email: string;
		emailTwo: string;
		phoneNumber: string;
		phoneNumberTwo: string;
		twitterLink: string;
		facebookLink: string;
		linkedinLink: string;
		copyrightText: string;
	};
	children: React.ReactNode;
}

const Layout: FC<ILayout> = ({
	children,
	pageTitle,
	footerMenuLinks,
	navbarMenuLinks,
	industriesMenuLinks,
	themesOptionsContent,
}) => {
	return (
		<>
			<Head>
				<title>{`${pageTitle} | Inventory Management Software`}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/Logos/BlueInventory favicon Two.png" />
			</Head>

			<Navbar
				navbarMenuLinks={navbarMenuLinks}
				themesOptionsContent={themesOptionsContent}
			/>

			<section className="pt-16">{children}</section>

			<Footer
				footerMenuLinks={footerMenuLinks}
				email={themesOptionsContent?.email}
				industriesMenuLinks={industriesMenuLinks}
				emailTwo={themesOptionsContent?.emailTwo}
				phoneNumber={themesOptionsContent?.phoneNumber}
				twitterLink={themesOptionsContent?.twitterLink}
				facebookLink={themesOptionsContent?.facebookLink}
				linkedinLink={themesOptionsContent?.linkedinLink}
				copyrightText={themesOptionsContent?.copyrightText}
				phoneNumberTwo={themesOptionsContent?.phoneNumberTwo}
			/>
		</>
	);
};

export default Layout;
