/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import HeroTwo from "../components/HeroTwo";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import HowItWorks from "../components/HowItWorks";
import CTATwo from "../components/CTATwo";
import FeaturesBanner from "../components/FeaturesBanner";

export default function FeaturesPage() {
	return (
		<>
			<Head>
				<title>Features | Inventory Management Software</title>
				<meta name="description" content="Generated by create next app" />
				{/* <!-- Website Icon --> */}
				<link rel="icon" href="/img/Logos/BlueInventory favicon Two.png" />
			</Head>

			<main className={styles.main}>
				{/* Hero Section */}
				<HeroTwo />

				{/* Feature Banner Section */}
				<FeaturesBanner />

				{/* CTA Two */}
				<CTATwo />

				{/* How It Works */}
				<HowItWorks />
			</main>
		</>
	);
}

// Removes Global Navbar & Adds Custom Header and Footer Page layout Function
FeaturesPage.getLayout = function PageLayout(page) {
	return (
		<>
			{/* <!--===== NAVBAR =====--> */}
			<Navbar />

			{/* <!--===== PAGE CONTENT =====--> */}
			{page}

			{/* <!--===== FOOTER =====--> */}
			<Footer />
		</>
	);
};
