/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Stats from "../components/stats";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import CTATwo from "../components/CTATwo";
import HeroTwo from "../components/HeroTwo";
import {contentfulContent} from "./api/api";
import CardGrid from "../components/CardGrid";
import JumboGrid from "../components/jumboGrid";
import styles from "../styles/Home.module.scss";
import FeaturesBanner from "../components/FeaturesBanner";

export default function FeaturesPage({featurePageContent}) {
	return (
		<>
			<Head>
				<title>{featurePageContent.featurePage}</title>
				<meta name="description" content="Generated by create next app" />
				{/* <!-- Website Icon --> */}
				<link rel="icon" href="/img/Logos/BlueInventory favicon Two.png" />
			</Head>

			<main className={styles.main}>
				{/* Hero Section */}
				<HeroTwo
					title={featurePageContent.heroTitle}
					subtitle={featurePageContent.heroSubtitle}
					backgroundImage={featurePageContent.heroImage.fields.file.url}
				/>

				{/* Stats */}
				<Stats />

				{/* Feature Banner Section */}
				<FeaturesBanner
					textOne={featurePageContent.textOne}
					textTwo={featurePageContent.textTwo}
					textThree={featurePageContent.textThree}
				/>

				{/*  */}
				<CardGrid />

				{/* How It Works */}
				<JumboGrid />
				{/* <HowItWorks title={howItWorks} data={howItWorks} /> */}

				{/* CTA Two */}
				<CTATwo
					title={featurePageContent.ctaTwoBannerTitle}
					paragraph={featurePageContent.ctaTwoBannerParagraph}
					buttonText={featurePageContent.ctaTwoBannerButtonText}
					buttonLink={featurePageContent.ctaTwoBannerButtonUrl}
				/>
			</main>
		</>
	);
}

// Removes Global Navbar & Adds Custom Header and Footer Page layout Function
FeaturesPage.getLayout = function PageLayout(page) {
	return (
		<>
			{/* <!--===== NAVBAR =====--> */}
			<Navbar />

			{/* <!--===== PAGE CONTENT =====--> */}
			{page}

			{/* <!--===== FOOTER =====--> */}
			<Footer />
		</>
	);
};

export async function getStaticProps() {
	const content = await contentfulContent("3kxkBngGv6SHwjkpFJEStB");

	return {
		props: {
			featurePageContent: content,
		},
	};
}
