/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Hero from "../components/Hero";
import CTAOne from "../components/CTAOne";
import TrustedBrands from "../components/TrustedBrands";

export default function Home() {
	return (
		<>
			<Head>
				<title>BlueInventory</title>
				<meta name="description" content="Generated by create next app" />
				{/* <!-- Website Icon --> */}
				<link rel="icon" href="/img/mainImages/B.png" />
			</Head>

			<main className={styles.main}>
				<div className="container mx-auto">
					{/*Hero Section */}
					<Hero />

					{/* Trusted Brands Logos */}
					<TrustedBrands />
				</div>

				{/*CTA One */}
				<CTAOne />
			</main>
		</>
	);
}
