/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Hero from "../components/Hero";
import CTAOne from "../components/CTAOne";
import TrustedBrands from "../components/TrustedBrands";
import HowItWorks from "../components/HowItWorks";

export default function Home() {
	return (
		<>
			<Head>
				<title>BlueInventory</title>
				<meta name="description" content="Generated by create next app" />
				{/* <!-- Website Icon --> */}
				<link rel="icon" href="/img/mainImages/B.png" />
			</Head>

			<main className={styles.main}>
				{/*Hero Section */}
				<Hero />

				{/* How It Works */}
				<HowItWorks />

				{/* Trusted Brands Logos */}
				<TrustedBrands />

				{/*CTA One */}
				<CTAOne />
			</main>
		</>
	);
}
