/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import FAQ from "../components/FAQ";
import Hero from "../components/Hero";
import CTAOne from "../components/CTAOne";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import CTATwo from "../components/CTATwo";
import {contentfulContent} from "./api/api";
import styles from "../styles/Home.module.scss";
import HowItWorks from "../components/HowItWorks";
import TrustedBrands from "../components/TrustedBrands";
import FeaturesBanner from "../components/FeaturesBanner";

const howItWorks = {
	title: "Our Services made simple",
	subtitle: "Connect your Inventory Without The Chaos",
	titleOne: "Be Always In Control.",
	titleTwo: "Keep updated all the time",
	titleThree: "Save Time And Money.",
	subtitleOne: "Create and Manage Inventory",
	subtitleTwo: "Track Related Products",
	subtitleThree: "Inventory Optimization",
	imageOne: "/img/pexels-rfstudio-3811082.jpg",
	imageTwo: "/img/pexels-jopwell-2422278.jpg",
	imageThree: "/img/pexels-rodnae-productions-5915209.jpg",
	textAreaOne:
		"Creating and managing inventory has never been easier. With powerful tools that integrate with popular devices. No more spending hours on spreadsheets to figure out what stock you have.",
	textAreaTwo:
		"Track inventory levels across a wide variety of products and calculate the costs of goods sold. Stop worrying about running out of stock - plan your inventory with absolute clarity",
	textAreaThree:
		"BlueInventory's inventory tracking software helps you find what is selling and what is not, saving you time and money by ensuring that your inventory is not only accurate, but has been prioritized.",
};

const trustedBrands = {
	title: "Trusted by brands",
	subtitle:
		"Making the process so simple providing unique features, solutions and an effective inventory management application.",
	imageOne: "/svg/Trusted Brands/jiggle-logo.svg",
	imageTwo: "/svg/Trusted Brands/resecurb-logo.svg",
	imageThree: "/svg/Trusted Brands/symtric-logo.svg",
	imageFour: "/svg/Trusted Brands/welytics-logo.svg",
	imageFive: "/svg/Trusted Brands/wishelp-logo.svg",
};

const trustedBrandsLogos = [
	"/svg/Trusted Brands/jiggle-logo.svg",
	"/svg/Trusted Brands/resecurb-logo.svg",
	"/svg/Trusted Brands/symtric-logo.svg",
	"/svg/Trusted Brands/welytics-logo.svg",
	"/svg/Trusted Brands/wishelp-logo.svg",
];

export default function HomePage({homePageContent}) {
	return (
		<>
			<Head>
				<title>{homePageContent.homePage}</title>
				<meta name="description" content="Generated by create next app" />
				{/* <!-- Website Icon --> */}
				<link rel="icon" href="/img/Logos/BlueInventory favicon Two.png" />
			</Head>

			<main className={styles.main}>
				{/* Hero Section */}
				{/* <Hero data={heroSectionContent} /> */}
				<Hero
					title={homePageContent.heroTitle}
					subtitle={homePageContent.heroSubtitle}
					ButtonTextOne={homePageContent.heroButtonTextOne}
					ButtonLinkOne={homePageContent.heroButtonOneUrl}
					ButtonTextTwo={homePageContent.heroButtonTextTwo}
					ButtonLinkTwo={homePageContent.heroButtonTwoUrl}
					backgroundImage={homePageContent.heroImage.fields.file.url}
				/>

				{/* Feature Banner Section */}
				<FeaturesBanner
					textOne={homePageContent.featureTextOne}
					textTwo={homePageContent.featureTextTwo}
					textThree={homePageContent.featureTextThree}
				/>

				{/* CTA Two */}
				<CTATwo />

				{/* How It Works */}
				<HowItWorks title={howItWorks} data={howItWorks} />

				{/* Trusted Brands Logos */}
				<TrustedBrands
					title={trustedBrands}
					data={trustedBrands}
					imagesArray={trustedBrandsLogos}
				/>

				{/* CTA One */}
				<CTAOne />

				{/* FAQ */}
				<FAQ />
			</main>
		</>
	);
}

// Removes Global Navbar & Adds Custom Header and Footer Page layout Function
HomePage.getLayout = function PageLayout(page) {
	return (
		<>
			{/* <!--===== NAVBAR =====--> */}
			<Navbar />

			{/* <!--===== PAGE CONTENT =====--> */}
			{page}

			{/* <!--===== FOOTER =====--> */}
			<Footer />
		</>
	);
};

export async function getStaticProps() {
	const content = await contentfulContent("190WQwlwr1Dhz9x91XNsGe");

	return {
		props: {
			homePageContent: content,
		},
	};
}
