// Imports
import {FC} from "react";
import Head from "next/head";
import {IDashBoardLayout} from "@/types/Dashboard/layout/indext";

const Layout: FC<IDashBoardLayout> = ({children, pageTitle}) => {
	return (
		<>
			<Head>
				<title>{`${pageTitle} | Inventory Management Software`}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/Logos/BlueInventory favicon Two.png" />
			</Head>

			{children}
		</>
	);
};

export default Layout;
